ethereum/evmc

- CMakeLists.txt
- circle.yml
- test/CMakeLists.txt
- test/vmtester/CMakeLists.txt
- test/vmtester/tests.cpp
- test/vmtester/vmtester.cpp
- test/vmtester/vmtester.hpp
Ready, but some git history cleanup might be needed.
Depends on #11.
> VM Tester tool

- CMakeLists.txt
- circle.yml
- examples/CMakeLists.txt
- examples/examplevm.c
- examples/examplevm/CMakeLists.txt
- examples/examplevm/examplevm.c
- test/vmtester/CMakeLists.txt
This refactors evmc-examplevm. On CI examplevm is build as a shared library and tested with vmtester.
> EVMC Example VM

- test/vmtester/vmtester.cpp
Nothing big here, I just realized that check a string prefix is quite simple in C++.
> vmtester: Simplify create function search

- include/evmc/evmc.h
- test/integration/CMakeLists.txt
- test/integration/compilation/CMakeLists.txt
- test/integration/compilation/compilation_test.c
- test/vmtester/CMakeLists.txt
Resolves https://github.com/ethereum/evmc/issues/19.
> Make header compilable in C99 and C11 pedantic mode

- .clang-format
- examples/capi.c
- examples/examplevm/examplevm.c
- test/integration/compilation/compilation_test.c
- test/vmtester/tests.cpp
- test/vmtester/vmtester.cpp
@axic are you fine with using clang-format config from cpp-ethereum / ethminer?
> Add clang-format config

- include/evmc/helpers.h
- include/evmc/instructions.h
- include/evmc/loader.h
- lib/loader/loader.c
- test/unittests/CMakeLists.txt
- test/unittests/test_loader.cpp
- test/unittests/vm_mock.c
- Fixes documentation.
- Add some helpers for EVMC and loader modules.
> Extensions

- include/evmc/utils.h
- test/integration/compilation/compilation_test.c
> utils: Properly resolve EVMC_EXPORT on mingw

- .bumpversion.cfg
- CMakeLists.txt
> Mark version 5.0.0-dev and add bumpversion config

- appveyor.yml
> AppVeyor CI: Test build of Go bindings

- CHANGELOG.md
- include/evmc/loader.h
- lib/loader/loader.c
- test/unittests/CMakeLists.txt
- test/unittests/test_loader.cpp
- test/unittests/vm_mock_default.c
> Fall back to evmc_create in the loader as a last resort

- circle.yml
- include/evmc/helpers.h
- include/evmc/loader.h
- lib/loader/loader.c
- test/integration/compilation/compilation_test.c
- test/integration/compilation/compilation_test.cpp
> CI: Check code format

- examples/capi.c
- examples/examplevm/CMakeLists.txt
- examples/examplevm/examplevm.c
> Use nicer example EVM bytecode in examples

- CHANGELOG.md
- docs/EVMC.md
- docs/VM_Tester.md
> docs: Add basic information about evmc-vmtester

- bindings/go/evmc/host.c
> go: Fix Host functions type checks

- bindings/go/evmc/evmc.go
- bindings/go/evmc/host.c
- examples/example_host.cpp
- examples/example_vm.c
- include/evmc/evmc.h
> Host interface

- bindings/go/evmc/evmc.go
> Go: support create2_salt

- bindings/go/evmc/evmc.go
- docs/EVMC.md
- examples/example_vm.c
- include/evmc/evmc.h
- include/evmc/helpers.h
- test/vmtester/tests.cpp
>  Introduce evmc_set_option_result enum

- docs/EVMC.md
- include/evmc/evmc.h
> Document versioning

- examples/example_vm.c
- test/vmtester/tests.cpp
> Add test for EVMC_SET_OPTION_INVALID_VALUE

- Doxyfile
- docs/EVMC.md
- docs/Host_Guide.md
- docs/VM_Guide.md
- examples/example_vm.c
- include/evmc/evmc.h
- include/evmc/helpers.h
The generated documentation: https://2594-66214407-gh.circle-artifacts.com/0/docs/index.html.
Closes #88
> VM Implementation Guide

- include/evmc/helpers.hpp
- test/unittests/test_helpers.cpp
Closes https://github.com/ethereum/evmc/issues/162.
> helpers: Add is_zero() helper

- docs/EVMC.md
Closes https://github.com/ethereum/evmc/issues/181.
> docs: Extend versioning description

- examples/example_vm.c
- examples/example_vm.h
- include/evmc/evmc.hpp
- lib/CMakeLists.txt
- test/unittests/CMakeLists.txt
- test/unittests/test_cpp.cpp
>  Add C++ wrappers/bindings for VM

- .bumpversion.cfg
- CHANGELOG.md
- CMakeLists.txt
Bump version: 6.1.0-dev → 6.1.0
> EVMC 6.1.0

- CHANGELOG.md
- include/evmc/evmc.hpp
- test/unittests/CMakeLists.txt
- test/unittests/test_cpp.cpp
Usage: https://github.com/chfast/evmone/commit/45ff329d29f0805b079d9a5c8beb1fee65f437db
> cpp: Add evmc::host - wrapper around Host context / interface

- test/vmtester/CMakeLists.txt
- test/vmtester/vmtester.cpp
> vmtester: Drop CLI11 dependency

- include/evmc/evmc.h
> Document expected UTF-8 encoding for .name and .version

- bindings/rust/evmc-vm/src/lib.rs
> rust: add ExecutionResult to stack evmc_result conversion

- examples/example-rust-vm/src/lib.rs
- examples/example_vm.c
- test/vmtester/tests.cpp
> vmtester: add test case for CREATE

- cmake/cable/CableBuildInfo.cmake
- cmake/cable/bootstrap.cmake
>  Upgrade Cable to 0.2.17 

- CHANGELOG.md
- circle.yml
- examples/example_host.cpp
- include/evmc/evmc.hpp
- test/unittests/test_cpp.cpp
> cpp: Fix Host::call()

- include/evmc/evmc.h
- include/evmc/helpers.h
- test/unittests/test_helpers.cpp
> Improve evmc_release_result() helper

- circle.yml
- include/evmc/evmc.h
> docs: Tweak documentation of evmc_execute_fn

- circle.yml
@chfast not sure this is useful, please feel free to close.
> Circle CI: Test for configuration validity of bumpversion

- README.md
> readme: Document limited C90 support

- CMakeLists.txt
- cmake/cable/CableBuildType.cmake
- cmake/cable/CableCompilerSettings.cmake
- cmake/cable/HunterGate.cmake
- cmake/cable/bootstrap.cmake
- examples/example_precompiles_vm/example_precompiles_vm.cpp
- include/evmc/evmc.hpp
- test/vmtester/vmtester.cpp
>  Do not shadow variable names 

- appveyor.yml
- test/integration/cmake_package/CMakeLists.txt
- test/unittests/CMakeLists.txt
- test/vmtester/CMakeLists.txt
Reduces AppVeyor time from 15 mins to 5 mins.
Some CMake cleanups also added.
Closes #291
> ci: Use Ninja on AppVeyor

- circle.yml
> Add LLVM sanitizers to Rust CI

- bindings/rust/evmc-declare/src/lib.rs
- circle.yml
- examples/example-rust-vm/src/lib.rs
> circleci: use ASan for vmtester with rust

- bindings/rust/evmc-declare/src/lib.rs
- bindings/rust/evmc-vm/src/lib.rs
> rust: add more comments/rustdoc

- CHANGELOG.md
- include/evmc/loader.h
- lib/loader/loader.c
- test/unittests/test_loader.cpp
Closes https://github.com/ethereum/evmc/issues/198.
> loader: Standarize EVMC module config

- CMakeLists.txt
- examples/CMakeLists.txt
- lib/instructions/CMakeLists.txt
- lib/loader/CMakeLists.txt
- test/vmtester/CMakeLists.txt
> cmake: Add option to disable install

- appveyor.yml
> ci: Store EVMC package on AppVeyor

- circle.yml
> circleci: test rust example vm with evmc-example

- bindings/rust/evmc-vm/src/lib.rs
Such as ExecutionResult and ExecutionMessage.
> rust: derive Debug trait on some abstractions

- bindings/rust/evmc-declare/src/lib.rs
- bindings/rust/evmc-vm/src/container.rs
Depends on #400.
@jakelang this is a cleanup I think it makes it easier to understand.
> rust: change ownership api in container 

- CHANGELOG.md
- README.md
> Update Changelog and README with Rust changes

- appveyor.yml
> ci: Add VS 2019 build on AppVeyor

- README.md
> readme: List testing tools

- examples/example_precompiles_vm/CMakeLists.txt
- examples/example_precompiles_vm/example_precompiles_vm.cpp
- examples/example_precompiles_vm/example_precompiles_vm.h
- examples/example_vm/CMakeLists.txt
- test/unittests/CMakeLists.txt
- test/unittests/test_cpp.cpp
- test/vmtester/tests.cpp
> Fixes for examples and unit tests

- CHANGELOG.md
- README.md
- bindings/rust/evmc-vm/src/lib.rs
- bindings/rust/evmc-vm/src/types.rs
- examples/example-rust-vm/src/lib.rs
> rust: add enum aliases

- circle.yml
> circleci: run clang-format on everything

- include/evmc/mocked_host.hpp
- test/unittests/mocked_host_test.cpp
> Make all EVMC Host methods of MockedHost public

- include/evmc/evmc.hpp
- test/unittests/cpp_test.cpp
> C++: Add uint64_t -> {bytes32, address} constructors

- circle.yml
Closes #471 by staying on CMake 3.10
> ci: Test build on Ubuntu 18.04 / Cmake 3.10

- bindings/rust/evmc-vm/src/lib.rs
> rust: use if let instead of if unwrap

- .bumpversion.cfg
- circle.yml
Closes #514 
Testrun of v8.0.0 bump: https://circleci.com/workflow-run/fced3540-1e23-43c2-9fb2-dcae6697664e
> go: Add go.mod to bumpversion

- CHANGELOG.md
- include/evmc/evmc.hpp
- test/unittests/cpp_test.cpp
> Rework literals implementation to use static_assert

- bindings/rust/evmc-sys/src/lib.rs
- bindings/rust/evmc-vm/src/container.rs
- bindings/rust/evmc-vm/src/lib.rs
> rust: some more cleanups suggested by clippy

- bindings/java/build.gradle
- bindings/java/wrapper.gradle
- circle.yml
- Upgrade Gradle to 7.5.1.
- Test with OpenJDK 18.
> Upgrade Java toolchain

- cmake/Hunter/config.cmake
- cmake/Hunter/init.cmake
- tools/evmc/main.cpp
This also upgrades CLI11 to 2.2.0.
> cmake: Upgrade Hunter to 0.24.3

- circle.yml
- test/unittests/cpp_test.cpp
- test/vmtester/CMakeLists.txt
> ci: Upgrade and clean up builds, add macOS

- circle.yml
> Migrate Windows CI to CircleCI

- bindings/go/evmc/host.c
- bindings/go/evmc/host.go
- bindings/java/c/host.c
- bindings/java/java/src/main/java/org/ethereum/evmc/Host.java
- bindings/java/java/src/main/java/org/ethereum/evmc/HostContext.java
- bindings/java/java/src/test/java/org/ethereum/evmc/TestHostContext.java
- bindings/rust/evmc-vm/src/container.rs
- bindings/rust/evmc-vm/src/lib.rs
- examples/example_host.cpp
- include/evmc/evmc.h
- include/evmc/evmc.hpp
- include/evmc/mocked_host.hpp
- test/unittests/cpp_test.cpp
All changes under `bindings` still todo
> Lookup CREATE4 tx initcodes by hash
