ethereum/evmc

- include/evmc.h
Fixes #16.
Actually addresses two things:
1. adding EVMC_PRECOMPILE_FAILURE
2. renaming EVMC_STATIC_MODE_ERROR
> Precompile failure

- examples/capi.c
- examples/examplevm/examplevm.c
- examples/examplevm/examplevm.h
- include/evmc.h
- test/vmtester/tests.cpp
- test/vmtester/vmtester.cpp
1. It introduces "name" and "version" fields in evmc_instance. This should be useful for dynamic loaded VM.
2. The naming convention for "create" function changed to be `evmc_create_` prefixed.
3. ABI version bumped to 1.
Fixes #10.
> EVMC ABI 1

- include/evmc.h
Would like to get this in before #23 so that it can be placed correctly in the order as well.
> include/evmc: add status code EVMC_CALL_DEPTH_EXCEDED

- examples/examplevm/examplevm.c
- include/evmc/evmc.h
- test/vmtester/CMakeLists.txt
- test/vmtester/tests.cpp
> Tracing API

- include/evmc/utils.h
Moved from https://github.com/ethereum/cpp-ethereum/blob/develop/libaleth-interpreter/interpreter.h#L11.
> Add EVMC_NOEXCEPT helper

- examples/capi.c
- include/evmc/evmc.h
Extend set_storage() by reporting the storage status.
Surprisingly, this was quite easy and aleth-interpreter is simpler and works without any test failure.
> Storage status

- Doxyfile
- README.md
- appveyor.yml
- docs/EVMC.md
- include/evmc/evmc.h
- include/evmc/utils.h
- Updates the EVMC module description and moves it to a markdown file.
- Some config tweaks for Doxygen.
- Documentation for macros from utils.h.
> Enhance documentation

- bindings/go/evmc/evmc.go
- bindings/go/evmc/evmc.h
- bindings/go/evmc/evmc_test.go
- bindings/go/evmc/helpers.h
- bindings/go/evmc/host.c
- bindings/go/evmc/host.go
- bindings/go/evmc/loader.c
- bindings/go/evmc/loader.h
- circle.yml
Can you help with the review @gballet, @fjl?
Appropriate go-ethereum PR: https://github.com/ethereum/go-ethereum/pull/17050
> Go bindings

- CHANGELOG.md
- include/evmc/evmc.h
> Add comment why the result is a pointer in release_result

- test/vmtester/CMakeLists.txt
- test/vmtester/mock_context.cpp
- test/vmtester/tests.cpp
Unfortunately need to adjust all the test VMs.
> Add vm test for execute

- appveyor.yml
- cmake/HunterConfig.cmake
- lib/loader/loader.c
Two issues with AppVeyor:
- Go has been upgraded to 1.11, this PR fixes #112.
- AppVeyor cache for Hunter stopped working, bump Hunter version to refresh it.
- Disable dev warnings in CMake.
> AppVeyor fixes

- CHANGELOG.md
- include/evmc/loader.h
- lib/loader/loader.c
Allow loader to shorten the name word by word to the point where only single word is left.
> Generalize loader searching algorithm

- include/evmc/evmc.h
The single "modified dirty" status is enough to implement EIP-1283, see https://github.com/ethereum/aleth/pull/5238
Closes https://github.com/ethereum/evmc/issues/91
> SSTORE net gas metering support

- bindings/go/evmc/host.c
- bindings/go/evmc/host.go
- examples/example_host.cpp
- include/evmc/evmc.h
> Add return code to get_block_hash_fn

- bindings/go/evmc/evmc.go
- examples/example.c
- include/evmc/evmc.h
- test/vmtester/tests.cpp
Resolves https://github.com/ethereum/evmc/issues/123.
Resolves https://github.com/ethereum/evmc/issues/122.
> Reorder evmc_message fields

- bindings/go/evmc/host.go
- include/evmc/evmc.h
> Rename EVMC_STORAGE_MODIFIED_DIRTY to EVMC_STORAGE_MODIFIED_AGAIN

- bindings/go/evmc/host.c
- bindings/go/evmc/host.go
- examples/example_host.cpp
- include/evmc/evmc.h
> Use bool type instead of int with 1 and 0

- bindings/go/evmc/host.c
- bindings/go/evmc/host.go
- examples/example_host.cpp
- include/evmc/evmc.h
> Return bool from some Host methods

- bindings/go/evmc/host.go
- examples/example_host.cpp
- include/evmc/evmc.h
> Update storage methods

- bindings/go/evmc/evmc.go
- bindings/go/evmc/host.c
- bindings/go/evmc/host.go
- examples/example.c
- examples/example_host.cpp
- examples/example_vm.c
- include/evmc/evmc.h
- test/vmtester/tests.cpp
Closes #121 
Some things to consider
- Add alias `evmc_hash256` for explicit crypto-hashes.
- Add alias `evmc_bytes32` and `evmc_address` to avoid `struct` prefix.
> Rename uint256be to bytes32

- Doxyfile
- examples/example_host.cpp
- include/evmc/helpers.h
- include/evmc/helpers.hpp
- test/unittests/CMakeLists.txt
- test/unittests/test_helpers.cpp
I actually implemented the same operators in Hera to simplify the contract preloading. It may just make sense exposing this here.
> Move C++ helpers into evmc/helpers.hpp

- bindings/go/evmc/host.c
- bindings/go/evmc/host.go
- examples/example_host.cpp
- examples/example_vm.c
- include/evmc/evmc.h
This reverts most of the Host method changes introduced recently.
Should I also change evmc_get_block_hash_fn?
I tried the previous API in Aleth and it is very messy. Here is an example of trying to expose the information if an account exists when checking balance: https://github.com/ethereum/aleth/pull/5261
This information is not useful in any of the use cases (no place where you would not to fold it to 0 balance).
> Simplify signatures of Host methods

- include/evmc/evmc.h
This specifies that the account which storage is to accessed or modified MUST exist.
> Clarify requirements for get/set storage methods

- circle.yml
- docs/EVMC.md
- docs/Host_Guide.md
Partly addresses #88.
Guide: https://2540-66214407-gh.circle-artifacts.com/0/docs/hostguide.html.
> docs: Host Implementation Guide

- bindings/go/evmc/host.c
- bindings/go/evmc/host.go
- examples/example_host.cpp
- include/evmc/evmc.h
Continuation of changes in #154.
> Simplify get_block_hash() method by returning null hash

- CMakeLists.txt
- README.md
- include/evmc/instructions.h
- include/evmc/loader.h
- test/integration/compilation/CMakeLists.txt
- test/integration/compilation/compilation_test.c
- test/integration/compilation/compilation_test.cpp
- Add tests for C90, C++14 and C++17.
- Make CMake macro, use OBJECT libraries.
- Include all public headers.
Closes: https://github.com/ethereum/evmc/issues/180.
> Enhance compilation tests

- CHANGELOG.md
- examples/use_instructions_in_cmake/use_instructions_in_cmake.c
- include/evmc/evmc.h
- test/unittests/test_instructions.cpp
- test/vmtester/tests.cpp
> Rename EVMC_LATEST_REVISION to EVMC_MAX_REVISION

- CHANGELOG.md
- include/evmc/evmc.h
Define EVMC_DEPRECATED attribute only for GCC 6+ because in older versions attributes cannot be applied to enum elements.
> Restrict the availability of EVMC_DEPRECATED

- CHANGELOG.md
- include/evmc/evmc.h
It looks like this: https://3432-66214407-gh.circle-artifacts.com/0/docs/group__EVMC.html#gae5759b1590071966ccf6a505b52a0ef7
> docs: Document elements of evmc_revision

- CHANGELOG.md
- bindings/go/evmc/evmc.go
- include/evmc/evmc.h
- lib/instructions/instruction_metrics.c
- lib/instructions/instruction_names.c
> Rename Constantinople2 to Petersburg

- bindings/rust/evmc-sys/build.rs
Output:
```
pub enum evmc_call_kind {
#[doc = "< Request CALL."]
EVMC_CALL = 0,
#[doc = "< Request DELEGATECALL. Valid since Homestead."]
#[doc = "The value param ignored."]
EVMC_DELEGATECALL = 1,
#[doc = "< Request CALLCODE."]
EVMC_CALLCODE = 2,
#[doc = "< Request CREATE."]
EVMC_CREATE = 3,
#[doc = "< Request CREATE2. Valid since Constantinople."]
EVMC_CREATE2 = 4,
}
```
> Always generate Rust enums

- .travis.yml
- appveyor.yml
- circle.yml
- cmake/HunterConfig.cmake
- examples/CMakeLists.txt
- lib/instructions/CMakeLists.txt
- test/unittests/CMakeLists.txt
This experiments with Travis CI / Windows.
It also fixes the hidden issue with running unit tests on Windows where it was missing the `example_vm.dll` but execution failure was silently ignored by the script.
Also Hunter is upgraded because it contains a fix for Travis CI/Windows environment.
> Add Travis CI for Windows

- examples/example_host.cpp
- include/evmc/evmc.hpp
- test/unittests/test_cpp.cpp
This adds the Host part of the C++ API.
The plan was different, to keep it physically separated, but I realized both Host and VM sides of the API implement the same interface... `HostInterface`.
This introduces some naming issues. We have
- `HostInterface` as pure C++ interface
- `HostContext` as wrapper for the host context pointer to be used by VMs, implements `HostInterface`.
- `Host` - the abstract class for Host implementations, implements `HostInterface`.
Suggestions for better names welcome.
Effectively closes https://github.com/ethereum/evmc/issues/189.
The only tunes left for C++ are aliases like `evmc::address = evmc_address`, merging helpers.hpp, maybe add better types for `evmc_address`, `evmc_uint256be`, etc.
> cpp: Add Host interface for the Host side

- bindings/go/evmc/evmc.go
- include/evmc/loader.h
- lib/loader/loader.c
- test/vmtester/CMakeLists.txt
- test/vmtester/vmtester.cpp
Only works on Linux and macos, otherwise returns null.
Closes #225.
> loader: Expose DLL load error

- bindings/rust/evmc-vm/src/lib.rs
> rust: Fix memory issues in ExecutionResult

- test/vmtester/vmtester.cpp
> vmtester: do not crash if create_vm returns nullptr

- Cargo.toml
- circle.yml
- examples/example-rust-vm/Cargo.toml
- examples/example-rust-vm/src/lib.rs
Part of #168.
Depends on #234.
> examples: Test Rust VM

- bindings/rust/evmc-vm/src/lib.rs
> rust: remove code duplication in ExecutionResult

- bindings/rust/evmc-vm/src/lib.rs
- examples/example-rust-vm/src/lib.rs
> Rust: Implement ExecutionContext

- CHANGELOG.md
- appveyor.yml
- test/unittests/test_instructions.cpp
- test/unittests/test_loader.cpp
- test/vmtester/tests.cpp
- test/vmtester/vmtester.hpp
Fixes #261 
This is GTest issue: https://github.com/google/googletest/issues/1616
> ci: Test C++17 mode in MSVC

- .bumpversion.cfg
- docs/EVMC.md
Couldn't yet get bumpversion to work properly.
> docs: add ABI version to the documentation 

- examples/CMakeLists.txt
- examples/example_precompiles_vm/CMakeLists.txt
- examples/example_precompiles_vm/example_precompiles_vm.cpp
- include/evmc/evmc.h
- test/vmtester/CMakeLists.txt
- test/vmtester/tests.cpp
>  Add experimental PRECOMPILES capability

- include/evmc/evmc.hpp
- test/integration/compilation/compilation_test.cxx
> cpp: Add missing '#pragma once' in evmc.hpp

- include/evmc/evmc.h
- include/evmc/evmc.hpp
- test/unittests/test_cpp.cpp
Closes https://github.com/ethereum/evmc/issues/265.
>  cpp: Add vm::get_capabilities() method 

- CHANGELOG.md
- lib/loader/loader.c
- test/unittests/test_loader.cpp
When a VM is loaded but turns out is has incompatible ABI version it should be destroyed before reporting the loading error and returning a null handle.
Fixes #305
> loader: Destroy VM with incompatible ABI 

- bindings/rust/evmc-vm/src/lib.rs
- examples/example-rust-vm/src/lib.rs
This handles the two common cases for VMs.
> rust: add failure() and success() helpers to ExecutionResult

- lib/loader/loader.c
- test/unittests/test_loader.cpp
The `strcpy_s() renamed to `strcpy_sx()` to indicate it is not the one from standard library.
The `strcpy_sx()` now reports errors and behaves as `strcpy_s()` when buffer is too small (nulls the buffer). But it does not have all the checks.
Fixes #304
> loader: Fix strcpy_s()

- examples/example_precompiles_vm/example_precompiles_vm.cpp
- test/vmtester/tests.cpp
> tests: add test case for precompile implementation 

- .bumpversion.cfg
- Cargo.toml
- bindings/rust/evmc-declare-tests/.gitignore
- bindings/rust/evmc-declare-tests/Cargo.toml
- bindings/rust/evmc-declare-tests/src/lib.rs
- bindings/rust/evmc-declare/.gitignore
- bindings/rust/evmc-declare/Cargo.toml
- bindings/rust/evmc-declare/src/lib.rs
- bindings/rust/evmc-vm/src/container.rs
- bindings/rust/evmc-vm/src/lib.rs
- examples/example-rust-vm/Cargo.toml
- examples/example-rust-vm/src/lib.rs
> Rust: Attribute-style procedural macro to generate EVMC FFI code with user-defined data

- bindings/rust/evmc-declare/src/lib.rs
> rust: unwind execution panics in evmc-declare

- circle.yml
- examples/example-rust-vm/Cargo.toml
This was such an annoying typo. More: https://doc.rust-lang.org/reference/linkage.html
> rust: compile examples for cdylib and not dylib 

- bindings/rust/evmc-declare-tests/src/lib.rs
- bindings/rust/evmc-declare/src/lib.rs
- bindings/rust/evmc-vm/src/container.rs
- examples/example-rust-vm/src/lib.rs
This should make @chfast happy (https://github.com/ethereum/evmc/pull/325#issuecomment-505371176).
> rust: fix some (mostly stylistic) warnings raised by rustc and clippy

- circle.yml
Use CircleCI 2.1 which allows creating groups of steps and reuse them in job specifications.
This change is mostly motivated by the #327 where I need to modify jobs for 32-bit builds but still want to use the common build steps.
> ci: Refactor Circle CI config

- test/unittests/test_instructions.cpp
Previously in the last iteration of the for loop the value EVMC_MAX_REVISION + 1 is assigned to rev of type evmc_revision what triggers an UBSan warning.
> test: Rewrite an unit test to avoid UBSan warning

- CHANGELOG.md
- appveyor.yml
- circle.yml
- include/evmc/helpers.hpp
- test/unittests/test_helpers.cpp
- test/vmtester/tests.cpp
> Add support for 32-bit architectures

- include/evmc/evmc.h
> docs: Clarify if execute() arguments can be NULLs

- bindings/rust/evmc-declare/src/lib.rs
Conforms (mostly) to #345. Precompiles capability is not properly supported as context is required and would mean a bigger refactoring.
> rust: allow empty code in evmc_execute()

- bindings/rust/evmc-vm/src/lib.rs
- bindings/rust/evmc-vm/src/types.rs
Part of #319.
Enums are handled in #206.
> rust: add type aliases for Address, Bytes32, Uint256

- bindings/rust/evmc-vm/src/lib.rs
> rust: use ExecutionMessage in ExecutionContext.call() 

- bindings/rust/evmc-declare-tests/src/lib.rs
- bindings/rust/evmc-declare/src/lib.rs
- bindings/rust/evmc-vm/src/container.rs
- bindings/rust/evmc-vm/src/lib.rs
- examples/example-rust-vm/src/lib.rs
Part of #318.
Also message is a key input to execution, it shouldn't be hidden inside the "frame context".
> rust: pass ExecutionMessage directly to EvmcVm.execute()

- CHANGELOG.md
- CMakeLists.txt
- cmake/Config.cmake.in
- cmake/EVMC.cmake
- examples/use_evmc_in_cmake/CMakeLists.txt
- test/vmtester/CMakeLists.txt
Closes https://github.com/ethereum/evmc/issues/296.
Requires #336, change the CMake command accordingly.
Required testing:
> cmake: Add helper for adding vmtester based VM test

- CHANGELOG.md
- examples/example_host.cpp
- include/evmc/evmc.hpp
- test/unittests/test_cpp.cpp
- test/unittests/test_helpers.cpp
- test/vmtester/tests.cpp
The basic types `address` and `bytes32` have received their C++ wrappers to assure they are always initialized. They also have convenient operator overloadings for comparison and usage as keys in standard containers.
Closes https://github.com/ethereum/evmc/issues/352
> C++: Add basic types based on C types

- CHANGELOG.md
- include/evmc/helpers.hpp
- test/unittests/CMakeLists.txt
- test/unittests/test_deprecated.cpp
- test/unittests/test_helpers.cpp
> Deprecate helpers.hpp

- CHANGELOG.md
- examples/example_vm/example_vm.c
- include/evmc/evmc.h
- include/evmc/helpers.h
> Deprecate tracing API

- CHANGELOG.md
- bindings/go/evmc/host.c
- bindings/go/evmc/host.go
- bindings/go/evmc/host_test.go
- examples/example_host.cpp
- examples/example_vm/example_vm.c
- include/evmc/evmc.h
- include/evmc/evmc.hpp
- include/evmc/helpers.h
- test/unittests/test_cpp.cpp
> cpp: Extend API for creating results

- .clang-format
- test/vmtester/vmtester.cpp
- test/vmtester/vmtester.hpp
The includes sorting config is taken from Aleth with regex for C++ standard library made more restrictive. The functional change is that .h and .hpp files are now equal.
> clang-format: Fix includes sorting

- circle.yml
- examples/CMakeLists.txt
- examples/example.c
Follow up of #365.
The reason I've started doing these changes is two fold:
- to give a better starter example for anyone implementing evmc host (e.g. learning from Solidity's trial and error)
- to test Rust example on CI
> examples: extend example to support dynamic loading

- bindings/rust/evmc-declare-tests/src/lib.rs
- bindings/rust/evmc-declare/src/lib.rs
- bindings/rust/evmc-vm/src/container.rs
- bindings/rust/evmc-vm/src/lib.rs
- examples/example-rust-vm/src/lib.rs
> rust: pass ExecutionContext mutable so it can actually be used with host functions

- circle.yml
- examples/example-rust-vm/src/lib.rs
- examples/example.c
Follow up of #388. Depends on #389.
> rust: implement the save_return_block_number example in example-rust-vm

- bindings/rust/evmc-vm/src/container.rs
- bindings/rust/evmc-vm/src/lib.rs
- examples/example-rust-vm/src/lib.rs
Fixes #370.
Ensures that execute() can borrow-check ExecutionContext correctly.
> rust: properly bind lifetimes in EvmcVm

- bindings/rust/evmc-declare/src/lib.rs
> Revert "rust: catch exceptions in the entire execute() wrapper"

- CHANGELOG.md
- cmake/cable/bootstrap.cmake
Fixes CMake issue in https://github.com/ewasm/hera/pull/550.
> Upgrade Cable to 0.4.4

- CHANGELOG.md
- include/evmc/helpers.hpp
The deprecated is_zero() is removed, but evmc.hpp is included in helpers.hpp in a way that allows using is_zero() as before. This is more user-friendly solution because now evmc::is_zero() can be used also for C types. Before, the deprecated overloading was selected by the compiler.
> cpp: Fallback to evmc::is_zero() in case the deprecated ::is_zero() is used

- CNAME
Finally figured out why we had an issue.
From [the support page](https://help.github.com/en/articles/troubleshooting-custom-domains#cname-already-taken):
> When you add or edit your custom domain in your GitHub Pages site's repository settings, we automatically create a CNAME file in the root of your repository.
So basically the setting was creating the file in the `gh-pages` branch, but our CircleCI task overwrites that from `master`, which didn't had the `CNAME` file.
> Add CNAME for evmc.ethereum.org alias

- cmake/Hunter/config.cmake
- cmake/Hunter/init.cmake
- test/CMakeLists.txt
- test/unittests/CMakeLists.txt
- test/unittests/test_cpp.cpp
- test/unittests/test_loader.cpp
- test/vmtester/tests.cpp
This is also fix builds with GCC9.
> cmake: Upgrade GTest to 1.8.1

- README.md
- test/integration/compilation/CMakeLists.txt
- test/integration/compilation/compilation_test.c
The support for C90 was accidentally broken in v6 in https://github.com/ethereum/evmc/commit/280ff9936308c2d07687bdf833485c5c63098d6f - C90 does not have _Bool type.
I don't see it as a problem in practice.
> Officially drop C90 standard support

- include/evmc/instructions.h
- lib/instructions/instruction_metrics.c
- test/unittests/test_instructions.cpp
> instructions: Set gas cost for undefined instructions to 0

- CHANGELOG.md
- include/evmc/evmc.hpp
- test/unittests/test_cpp.cpp
- test/vmtester/vmtester.cpp
- test/vmtester/vmtester.hpp
> cpp: Rename evmc::vm to evmc::VM

- bindings/go/evmc/evmc.go
- bindings/go/evmc/host.c
- bindings/go/evmc/host.go
- bindings/rust/evmc-declare/src/lib.rs
- bindings/rust/evmc-vm/src/container.rs
- bindings/rust/evmc-vm/src/lib.rs
- docs/Host_Guide.md
- examples/example.c
- examples/example_host.cpp
- examples/example_host.h
- examples/example_precompiles_vm/example_precompiles_vm.cpp
- examples/example_vm/example_vm.c
- include/evmc/evmc.h
- include/evmc/evmc.hpp
- include/evmc/helpers.h
- test/unittests/test_cpp.cpp
- test/vmtester/tests.cpp
> Rename evmc_context to evmc_host_context

- bindings/rust/evmc-declare/src/lib.rs
- bindings/rust/evmc-vm/src/container.rs
- examples/example_precompiles_vm/example_precompiles_vm.cpp
- include/evmc/evmc.h
- include/evmc/helpers.h
- test/unittests/test_cpp.cpp
- test/unittests/test_loader.cpp
- test/vmtester/tests.cpp
> Remove deprecated tracing API

- CHANGELOG.md
- lib/loader/loader.c
- test/unittests/test_loader.cpp
This should fix https://github.com/ethereum/evmone/pull/199 where the library file has name `libevmone.so.0.3.0`.
Fixes https://github.com/ethereum/evmc/issues/436.
> loader: Trim all file extensions for create function name

- CHANGELOG.md
- circle.yml
- examples/CMakeLists.txt
- examples/example_precompiles_vm/CMakeLists.txt
- examples/example_vm/CMakeLists.txt
- include/evmc/loader.h
- lib/loader/loader.c
- test/unittests/CMakeLists.txt
- test/unittests/test_loader.cpp
- test/vmtester/CMakeLists.txt
The loader library no longer tries EVMC create function names with removed prefixes.
> loader: Simplify logic for finding create function

- CHANGELOG.md
- bindings/go/evmc/evmc.go
- bindings/go/evmc/host.go
- bindings/rust/evmc-declare/src/lib.rs
- bindings/rust/evmc-sys/build.rs
- bindings/rust/evmc-sys/src/lib.rs
- bindings/rust/evmc-vm/src/container.rs
- bindings/rust/evmc-vm/src/lib.rs
- examples/example.c
- examples/example_host.cpp
- examples/example_host.h
- examples/example_precompiles_vm/example_precompiles_vm.cpp
- examples/example_vm/example_vm.c
- include/evmc/evmc.h
- include/evmc/evmc.hpp
- include/evmc/helpers.h
- test/unittests/test_cpp.cpp
- test/vmtester/tests.cpp
On the C API level (and also ABI) the `host_interface` (think: an object vtable) and `host_context` (think: pointer to an object's data) are separated. This actually makes creating language bindings easier - no need for workarounds as in https://github.com/ethereum/evmc/blob/master/bindings/go/evmc/evmc.go#L26-L30.
Language bindings can still hide this by providing single OOP interface for Host (both for Client and VM side).
> Move evmc_host_interface out of evmc_host_context

- CHANGELOG.md
- bindings/rust/evmc-declare-tests/src/lib.rs
- bindings/rust/evmc-declare/src/lib.rs
- bindings/rust/evmc-vm/src/container.rs
- bindings/rust/evmc-vm/src/lib.rs
- examples/example-rust-vm/src/lib.rs
> rust: make ExecutionContext optional in EvmcVm.execute()

- CHANGELOG.md
- include/evmc/evmc.hpp
- test/unittests/test_cpp.cpp
Closes https://github.com/ethereum/evmc/issues/299. Part of #259.
> C++: Add execute() overloading without evmc_context parameter

- examples/example_host.cpp
- include/evmc/evmc.hpp
- test/unittests/test_cpp.cpp
> Tweaks to C++ API

- include/evmc/evmc.hpp
- test/unittests/test_cpp.cpp
This fixes issue reported in https://github.com/ethereum/evmc/pull/445#discussion_r343150374.
One method is left outside of the class definition to workaround doxygen bug.
Also added unit tests for previously unused APIs.
> C++ API tweaks (part 2)

- CHANGELOG.md
- include/evmc/evmc.hpp
- test/unittests/test_cpp.cpp
Pass `evmc_host_interface` by reference to `evmc::HostContext` to make explicit that this pointer must not be null.
> cpp: Require the host interface for HostContext be passed by reference

- include/evmc/evmc.h
Was working on Java bindings and noticed in `include/evmc/evmc.h`:
Comment on `evmc_get_code_hash_fn` was
```
Get code size callback function.
```
changed to 
```
Get code hash callback function.
```
> Fix comment on evmc_get_code_hash_fn

- CHANGELOG.md
- include/evmc/mocked_host.hpp
- lib/CMakeLists.txt
- lib/mocked_host/CMakeLists.txt
- test/integration/compilation/compilation_test.cxx
- test/unittests/test_cpp.cpp
It takes the MockedHost implementation from evmone and creates an interface library out of it.
Part of #447.
> Add mocked_host library

- include/evmc/mocked_host.hpp
- test/unittests/test_cpp.cpp
This is needed by soltest's implementation of create and its related tests.
> mocked_host: add nonce to account

- circle.yml
- include/evmc/mocked_host.hpp
This simply moves `storage_value` struct out of `MockedAccount` struct. Fix is a workaround for a clang 5 compiler bug.
Fixes #467.
> Fix build with clang 5

- CHANGELOG.md
- CMakeLists.txt
- examples/CMakeLists.txt
- examples/example_precompiles_vm/CMakeLists.txt
- examples/example_vm/CMakeLists.txt
- lib/CMakeLists.txt
- lib/instructions/CMakeLists.txt
- lib/loader/CMakeLists.txt
- lib/mocked_host/CMakeLists.txt
- test/unittests/CMakeLists.txt
This mostly adds `evmc::evmc_cpp` target representing C++ headers. It also contains some dependency cleanups.
> CMake improvements

- bindings/rust/evmc-declare/Cargo.toml
- bindings/rust/evmc-vm/Cargo.toml
Closes #475.
This is needed to publish the crates.
> rust: version dependencies

- CHANGELOG.md
- CMakeLists.txt
- circle.yml
- codecov.yml
- test/CMakeLists.txt
- test/tools/CMakeLists.txt
- tools/CMakeLists.txt
- tools/evmc/CMakeLists.txt
- tools/evmc/main.cpp
- tools/evmc/utils.cpp
- tools/evmc/utils.hpp
A first version of the EVMC runner tool.
1. We want a single tool `evmc` with subcommands. This one adds the main tool with `run` command.
2. Later we will move the `evmc-vmtester` here probably as `evmc check-vm`.
3. This uses CLI11 library for parsing command line options.
4. I tried to move the `run` command to separate file, but it gets messy a bit. We may try it later, but this might not be good idea in general. Moreover, building every file including `CLI.hpp` takes ~2s.
5. We should move hex helpers from evmone here. But C++17 would be nice for it to have `string_view`. There is a way to specify that only some CMake targets require C++17.
Closes #447.
> EVMC runner tool

- CMakeLists.txt
- We are using GoogleTest module introduced in 3.9.
- None of Debian / Ubuntu distributions versions provides CMake 3.9. The 3.10 is selected because this is the version provided in Ubuntu 18.04 LTS.
> cmake: Bump minimum required version to 3.10

- CMakeLists.txt
- circle.yml
- examples/example_precompiles_vm/CMakeLists.txt
- lib/CMakeLists.txt
- test/unittests/CMakeLists.txt
This removes mandatory usage of CMake toolchain files. Instead it is now specified that C++ libraries require C++11, but the C++ standard is not forced.
> CMake improvements 2

- CHANGELOG.md
- include/evmc/evmc.hpp
- test/unittests/cpp_test.cpp
"load64be(&a.bytes[8]) == load64be(&b.bytes[8])" requires "load64be(&a.bytes[0]) == load64be(&b.bytes[0]" as well, check if load64be(&a.bytes[0]) > load64be(&b.bytes[0] and "load64be(&a.bytes[8]) == load64be(&b.bytes[8])"
> fix less compare for address and bytes32

- bindings/java/Makefile
- bindings/java/build.gradle
- bindings/java/wrapper.gradle
- circle.yml
This is Java build system maintenance work and to fix my local build based on OpenJDK 13. I believe Gradle 6 is needed for OpenJDK 13.
There are some additional questions:
- The `build/evmc.jar` (produced by gradle?) is empty.
- I can build `evmc.so` with JNI using CMake. That would be preferable than using the custom Makefile.
- I can also build `evmc.jar` with CMake. So we may only need gradle to do testing (get JUnit5) and "spotless"?
> java: Build update

- CHANGELOG.md
- bindings/java/c/evmc-vm.c
- bindings/java/c/host.c
- bindings/java/c/host.h
Similarly to how we prefix with evmc_go_ in the go bindings.
See https://github.com/ethereum/evmc/blob/master/bindings/go/evmc/host.c#L16.
Probably it doesn't matter too much as long as the `bindings/java/c` directory is a compiled to a single shared library, which I think it is.
> java: prefix C exports with evmc_java_

- CHANGELOG.md
- appveyor.yml
- bindings/go/evmc/evmc.go
- bindings/go/evmc/evmc_test.go
- bindings/go/evmc/host.go
- bindings/go/evmc/host_test.go
- circle.yml
Continuation of #499.
I added a change not to define `{address,hash}Length` constants. To me this looks fine.
Because of the change I would just move the `Address` and `Hash` types to `evmc.go`.
> go: Remove dependencies on go-ethereum

- CHANGELOG.md
- README.md
- appveyor.yml
- bindings/go/evmc/evmc.go
- bindings/go/evmc/evmc.h
- bindings/go/evmc/helpers.h
- bindings/go/evmc/host.go
- bindings/go/evmc/loader.c
- bindings/go/evmc/loader.h
- circle.yml
- go.mod
- test/gomod/.gitignore
- test/gomod/README
- test/gomod/use_evmc_test.go
Go modules support by @mandrigin.
Closes #450
> go: Add Go modules support

- README.md
- appveyor.yml
- lib/CMakeLists.txt
- test/compilation/CMakeLists.txt
Bump C++ standard required from C++11 to C++14. This also drops support
for Visual Studio 2015.
> cpp: Require C++14

- bindings/rust/evmc-sys/build.rs
This removes any stray types added by the local system, such as "stdint" on macOS.
> rust: only allow whitelisted types in the generated bindings

- circle.yml
This disables running gomod integration test in PRs from forked repos. It was expected this test not to work as it would require to pull the commit from the fork as the version of `github.com/ethereum/evmc` module.
The same commit from withing `ethereum/evmc` repo: https://circleci.com/gh/ethereum/evmc/24915.
> ci: Skip gomod integration test in "PRs from forks"

- circle.yml
The intention is to skip the test for external PRs as `go mod` does not work for fork repos. But the original script incorrectly used subshell instead of block of commands.
Proof it works now: https://app.circleci.com/pipelines/github/ethereum/evmc/1312/workflows/8dd17f41-baf4-46f8-9b4e-fe2d12e6f4b3/jobs/25360/parallel-runs/0/steps/0-104
> ci: Fix Gomod integration test

- bindings/java/java/src/main/java/org/ethereum/evmc/Host.java
Peeling off a change from #532 to single it out. This fixes a bug in how Java interfaces with JNI. JNI requires a direct buffer allocation instead of a heap bytebuffer.
> java: Use allocateDirect instead of wrap in copy_code

- bindings/java/c/host.c
Remove all the checks for jenv in the bindings code. If jenv is not there, it's better to crash.
> java: Remove all the unnecessary JNIEnv checks

- bindings/go/evmc/evmc.go
- include/evmc/evmc.h
- tools/evmc/utils.cpp
EVMC_BALANCE_TOO_LOW describes the situation when the caller doesn't have enough funds for value transfer. Useful on the host side for CREATE, CALL and ilk.
> Add EVMC_INSUFFICIENT_BALANCE error to evmc_status_code

- tools/CMakeLists.txt
- tools/evmc/CMakeLists.txt
- tools/evmc/main.cpp
- tools/utils/CMakeLists.txt
- tools/utils/utils.cpp
- tools/utils/utils.hpp
Move utils.{hpp,cpp} files to new evmc::tool-utils static library.
It is going to be used in unit tests.
> cmake: Extract evmc::tool-utils out of evmc::tool

- circle.yml
- test/CMakeLists.txt
- test/examples/CMakeLists.txt
Include EVMC examples tests in CTest.
> cmake: Add example end-to-end tests to CTest

- bindings/java/c/evmc-vm.c
- bindings/java/c/host.c
- bindings/java/c/host.h
- bindings/java/java/src/main/java/org/ethereum/evmc/EvmcVm.java
- bindings/java/java/src/main/java/org/ethereum/evmc/Host.java
> java: remove the extra wrapping of HostContext and pass it directly

- include/evmc/evmc.hpp
When comparing equal, byteswap is not necessary so don't suggest it to the compiler.
> C++: Optimize EVMC types comparison

- circle.yml
- include/evmc/evmc.hpp
- test/unittests/CMakeLists.txt
- test/unittests/tool_commands_test.cpp
- tools/CMakeLists.txt
- tools/commands/CMakeLists.txt
- tools/commands/commands.hpp
- tools/commands/run.cpp
- tools/evmc/CMakeLists.txt
- tools/evmc/main.cpp
This move the implementation of "run" command from the `evmc` tool to separate library. This allows provide unit tests for this command.
> Testable tool commands

- .clang-format
- Doxyfile
- bindings/go/evmc/evmc_test.go
- bindings/go/evmc/host_test.go
- bindings/java/java/src/test/java/org/ethereum/evmc/EvmcTest.java
- circle.yml
- docs/VM_Guide.md
- examples/example_vm/CMakeLists.txt
- examples/example_vm/example_vm.cpp
- include/evmc/evmc.hpp
- test/gomod/README
- test/tools/CMakeLists.txt
- test/unittests/CMakeLists.txt
- test/unittests/cpp_test.cpp
- test/unittests/example_vm_test.cpp
- test/unittests/tool_commands_test.cpp
This allows simpler and much readable implementation. The goal is to stay close to C.
This is going to be useful to test `evmc run` for options like `--input` and `--deploy`.
This however requires users like Go and Java to build the `example-vm.so` as C++. This bumps runtime requirements to include C++ standard library.
Fixes #364.
> examples: Convert example VM implementation to C++

- test/tools/CMakeLists.txt
- tools/evmc/main.cpp
```
> bin/evmc --version --vm ~/Projects/ethereum/evmone/build/debug/lib/libevmone.so
evmone 0.6.0-dev (/home/chfast/Projects/ethereum/evmone/build/debug/lib/libevmone.so)
EVMC 7.5.0-alpha.0 (bin/evmc)
```
> tools: Include VM name and version in evmc --version

- bindings/rust/evmc-sys/build.rs
The referred problems were fixed.
> rust: remove obsolete bindgen commands

- include/evmc/evmc.hpp
- test/unittests/cpp_test.cpp
This replaces the big-endian loads with little-endian loads in hash functions for `evmc::address` and `evmc::bytes32`.
Performance improvements are significant.
```
hash_<evmc::bytes32, hash<evmc::bytes32>>_mean                           -0.2973         -0.2973          2335          1641          2335          1641
hash_<evmc::bytes32, noinline_hash<evmc::bytes32>>_mean                  -0.1559         -0.1559          3045          2571          3045          2571
hash_<evmc::address, hash<evmc::address>>_mean                           -0.4009         -0.4009          1323           793          1323           793
hash_<evmc::address, noinline_hash<evmc::address>>_mean                  -0.2762         -0.2762          1955          1415          1955          1415
```
Originally, I also …
> C++: Use simpler 3a + b folding in std::hash

- tools/commands/CMakeLists.txt
Otherwise evmone build fails on Windows: https://ci.appveyor.com/project/chfast/evmone/builds/37856416
> Make tool-commands lib STATIC similar to tool-utils

- test/tools/CMakeLists.txt
- test/unittests/tool_commands_test.cpp
- tools/commands/commands.hpp
- tools/commands/run.cpp
- tools/evmc/main.cpp
```shell=
> bin/evmc run -h
Execute EVM bytecode
Usage: bin/evmc run [OPTIONS] code
Positionals:
code TEXT REQUIRED          Hex-encoded bytecode
Options:
-h,--help                   Print this help message and exit
--gas INT:INT in [0 - 1000000000]=1000000
Execution gas limit
--rev ENUM=7                EVM revision
--input TEXT                Hex-encoded input bytes
--create                    Create new contract out of the code and then execute this contract with the input
```
> Add --create option to `evmc run`

- bindings/java/java/src/main/java/org/ethereum/evmc/EvmcVm.java
> java: EvmcVm.close does not throw exception

- bindings/java/Makefile
- bindings/java/build.gradle
- bindings/java/java/src/main/java/org/ethereum/evmc/EvmcLoaderException.java
- bindings/java/java/src/main/java/org/ethereum/evmc/EvmcVm.java
- bindings/java/java/src/main/java/org/ethereum/evmc/Host.java
- circle.yml
Fixes https://github.com/ethereum/evmc/pull/559#discussion_r516536807
> java: add proper lint task to CI

- bindings/java/java/src/main/java/org/ethereum/evmc/EvmcLoaderException.java
- bindings/java/java/src/main/java/org/ethereum/evmc/EvmcVm.java
Pulled out of #555.
#555 will ultimate replace the code in `create()`, but nevertheless this seems to be a nice intermediate step we can merge now, while #555 could take a bit of work 😬
> java: do not abort, but throw an exception in all cases in EvmcVm.create()

- bindings/java/Makefile
- bindings/java/java/src/main/java/org/ethereum/evmc/EvmcVm.java
- bindings/java/java/src/test/java/org/ethereum/evmc/EvmcTest.java
This should implement the pattern of storing the shared object in the JAR file, copying it to a temp folder, and loading it from there.
> java: statically load JNI library

- bindings/java/c/evmc-vm.c
- bindings/java/java/src/main/java/org/ethereum/evmc/EvmcVm.java
This could be replaced with just passing buffers allocated based on #555.
Part of #548.
> java: allocate execute result in C

- circle.yml
This reverts commit 29dcf2381855e3927791cda587bc60e8a67ff1f4
because the Rust nightly regression has been fixed.
https://github.com/rust-lang/rust/pull/84130
> Revert "ci: Pin Rust nightly version"

- Doxyfile
- circle.yml
- examples/example_host.cpp
- include/evmc/evmc.hpp
- Upgrade some compilers to latest version,
- Upgrade doxygen,
- Upgrade clang-format
> ci: Upgrade and cleanup compilers/executors

- bindings/go/evmc/evmc.go
- include/evmc/evmc.h
- lib/instructions/instruction_metrics.c
- lib/instructions/instruction_names.c
- test/unittests/instructions_test.cpp
- tools/evmc/main.cpp
- tools/utils/utils.cpp
Add `evmc_revision` value for the upcoming [London fork](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/mainnet-upgrades/london.md).
> Add EVMC_LONDON revision

- CMakeLists.txt
- circle.yml
- test/unittests/CMakeLists.txt
- tools/evmc/CMakeLists.txt
- tools/vmtester/CMakeLists.txt
This outputs all EVMC executables in top-level /bin build dir. So for parent projects like evmone e.g. `evmc` will be located in `build/bin/evmc` (`build/evmc/bin/evmc` previously).
The output dir can be changes with standard `-DCMAKE_RUNTIME_OUTPUT_DIRECTORY`.
evmone check: https://github.com/ethereum/evmone/pull/330.
> cmake: Output executables to top-level /bin dir

- include/evmc/evmc.h
- test/tools/CMakeLists.txt
- tools/evmc/main.cpp
```c
/**
* The latest known EVM revision with finalized specification.
*
* This is handy for EVM tools to always use the latest revision available.
*/
EVMC_LATEST_STABLE_REVISION = EVMC_LONDON
```
> Add EVMC_LATEST_STABLE_REVISON

- bindings/go/evmc/evmc.go
- bindings/go/evmc/evmc_test.go
Added a test that fails in case of `C.EVMC_MAX_REVISION` is increased as a remainder to add new Revision constants to Go.
> evmc_test.go:65: missing constant for revision 10
The missing London Revision is added.
> go: Add missing Shanghai revision constant

- bindings/go/evmc/evmc.go
- bindings/go/evmc/evmc_test.go
Use C's `evmc_status_code_to_string()` instead of producing error messages manually in Go.
> go: Use C.evmc_status_code_to_string() for error messages

- CHANGELOG.md
- bindings/go/evmc/evmc.go
- bindings/go/evmc/evmc_test.go
- bindings/go/evmc/host_test.go
- include/evmc/evmc.h
> go: create2_salt is not required for execution

- bindings/go/evmc/evmc.go
- bindings/go/evmc/host.go
- bindings/go/evmc/host_test.go
- bindings/java/java/src/test/java/org/ethereum/evmc/TestMessage.java
- bindings/rust/evmc-vm/src/container.rs
- bindings/rust/evmc-vm/src/lib.rs
- include/evmc/evmc.h
- tools/vmtester/tests.cpp
Without code address `evmc_message` is not enough to implement `evmc_call_fn` for the DELEGATECALL case. For more detail please see https://github.com/torquem-ch/silkworm/pull/286.
**_Warning:_ This is an API breaking change and requires a major version bump!**
Related PRs: https://github.com/ethereum/evmone/pull/360 and https://github.com/torquem-ch/silkworm/pull/288.
> Add code_address to evmc_message

- examples/example_precompiles_vm/example_precompiles_vm.cpp
- include/evmc/evmc.h
- test/unittests/cpp_test.cpp
- tools/vmtester/tests.cpp
- Clarifies the documentation around `evmc_message::code_address` and other `evmc_message` fields.
- Fixes the usage of `code_address` vs `destination` in the "precompiles vm" example.
- Resolves the issue reported in https://github.com/ethereum/evmc/pull/611#discussion_r702855921.
> Clarify evmc_message::code_address usage

- bindings/go/evmc/evmc.go
- bindings/java/c/evmc-vm.c
- include/evmc/loader.h
- test/unittests/loader_test.cpp
- tools/evmc/main.cpp
- tools/vmtester/vmtester.cpp
Introduce special loader error code EVMC_LOADER_UNSPECIFIED_ERROR
for initializing evmc_loader_error_code objects. This allows defensive
usage pattern where user init error code to a value other than
EVMC_LOADER_SUCCESS what protects against a misbehaving loader
implementation.
Go and Java bindings use new value. Rust bindings do not have EVMC loader support.
> loader: Introduce error code for initialization

- lib/loader/loader.c
This at least confuses static analyzers.
> loader: Do not repeat strlen(options) condition

- CHANGELOG.md
- include/evmc/evmc.hpp
The C++ API for HostContext was caching the tx context. The caching seems good idea, but the EVM might want to do it its own way, but it is inconvenient if it cannot change the behavior here.
So this change is removing this responsibility from C++ API.
> C++: Do not cache tx context in HostContext

- CHANGELOG.md
- bindings/go/evmc/evmc.go
- include/evmc/evmc.h
- include/evmc/helpers.h
- lib/instructions/instruction_metrics.c
- lib/instructions/instruction_names.c
- test/unittests/cpp_test.cpp
- test/unittests/instructions_test.cpp
To reflect the rename in the official spec.
https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md
https://github.com/ethereum/execution-specs/commit/79daccf7e1ef028d48ba02c29c347af4b98fc696
https://github.com/ethereum/pm/issues/491
> Rename Merge revision to Paris

- include/evmc/evmc.hpp
- test/unittests/cpp_test.cpp
This change allows passing `address` and `bytes32` objects to functions taking `bytes_view` as argument.
> C++: Conversion {address, bytes32} → bytes_view

- bindings/rust/evmc-declare/README.md
- bindings/rust/evmc-sys/README.md
- bindings/rust/evmc-vm/README.md
These are useful to show some content on crates.io, e.g. https://crates.io/crates/evmc-vm
> rust: Add READMEs to each of the crates

- README.md
- bindings/rust/evmc-sys/Cargo.toml
- bindings/rust/evmc-sys/build.rs
This also bumps the Rust minimum version requirement from 1.37 to 1.47
Co-authored-by: Artem Vorotnikov <artem@vorotnikov.me>
> rust: Update bindgen to 0.59

- bindings/rust/evmc-sys/build.rs
- bindings/rust/evmc-sys/src/lib.rs
> rust: turn evmc_host_context into a void type

- examples/example_host.cpp
- include/evmc/evmc.hpp
- test/unittests/cpp_test.cpp
Remove support for 0_{address,bytes32} literals. This feature is not frequently used.
> C++: Remove 0_{address,bytes32} literals

- include/evmc/tooling.hpp
- lib/tooling/run.cpp
- test/tools/CMakeLists.txt
- test/unittests/tooling_test.cpp
- tools/evmc/main.cpp
For `--input` and `code` arguments allow loading data from a file by preceding the file path with @ character. E.g. `--input @sha1.in`.
Change the type of code and input parameters of `tooling::run()` from hex-encoded string to bytes. The hex decoding must happen outside. This moves the hex decoding errors out of the function concern.
> tool: Use @file syntax to loading data from a file

- bindings/java/c/host.c
- bindings/java/java/src/main/java/org/ethereum/evmc/Host.java
It used to have a typo triggering get_code_hash. Also removed the _fn suffix.
Pulled from #651.
> java: Fix get_block_hash implementation

- include/evmc/hex.hpp
- test/unittests/CMakeLists.txt
- test/unittests/filter_iterator_test.cpp
- test/unittests/hex_test.cpp
- test/unittests/tooling_test.cpp
- tools/evmc/CMakeLists.txt
- tools/evmc/filter_iterator.hpp
- tools/evmc/main.cpp
Generalize the `core from_hex()` to take the input as pair in input iterators. The optional 0x prefix is still omitted but the "skip space" feature has been dropped.
Add `skip_space_iterator`. This restores the option to filter-out whitespace before parsing hex. This is useful e.g. when loading hex from a file.
> Refactor hex decoding utilities

- include/evmc/hex.hpp
- test/unittests/hex_test.cpp
> hex: Add from_hex<T> for user types

- CHANGELOG.md
- examples/example_host.cpp
- include/evmc/evmc.h
- include/evmc/evmc.hpp
- test/unittests/cpp_test.cpp
New constructors are added based on the usage in state transition implementation in evmone.
> C++: Add convenient result constructors

- CHANGELOG.md
- examples/example_host.cpp
- include/evmc/evmc.hpp
- include/evmc/mocked_host.hpp
- lib/tooling/run.cpp
- test/unittests/cpp_test.cpp
- test/unittests/example_vm_test.cpp
Rename the `evmc::result` to `evmc::Result` for consistency with C++ types of similar kind.
> C++: Rename evmc::result → evmc::Result

- CHANGELOG.md
- bindings/go/evmc/host.c
- bindings/go/evmc/host.go
- bindings/go/evmc/host_test.go
- bindings/java/c/host.c
- bindings/java/java/src/main/java/org/ethereum/evmc/Host.java
- bindings/java/java/src/main/java/org/ethereum/evmc/HostContext.java
- bindings/java/java/src/test/java/org/ethereum/evmc/TestHostContext.java
- bindings/rust/evmc-vm/src/lib.rs
- examples/example_host.cpp
- include/evmc/evmc.h
- include/evmc/evmc.hpp
- include/evmc/mocked_host.hpp
- test/unittests/cpp_test.cpp
- test/unittests/mocked_host_test.cpp
Return from the selfdestruct method the information if the given address
has not been registered as selfdestructed yet.
> Report duplicated selfdestructs back to EVM

- CHANGELOG.md
- bindings/go/evmc/host.go
- bindings/go/evmc/host_test.go
- bindings/rust/evmc-vm/src/types.rs
- docs/EVM_Storage_Change_Status.md
- examples/example_host.cpp
- include/evmc/evmc.h
- include/evmc/mocked_host.hpp
- test/unittests/cpp_test.cpp
- test/unittests/example_vm_test.cpp
- test/unittests/mocked_host_test.cpp
Expand the number of storage statuses to cover all possible EVM
behaviors. These provide enough information to VM to compute not only
gas costs but also refunds. Including legacy SSTORE costs before net
gas metering.
> Extend storage status

- CHANGELOG.md
- bindings/go/evmc/host.go
- bindings/go/evmc/host_test.go
- bindings/java/Makefile
- bindings/java/c/host.c
- bindings/java/java/src/test/java/org/ethereum/evmc/TestHostContext.java
- bindings/rust/evmc-declare-tests/src/lib.rs
- bindings/rust/evmc-declare/src/lib.rs
- bindings/rust/evmc-sys/src/lib.rs
- bindings/rust/evmc-vm/src/lib.rs
- examples/example-rust-vm/src/lib.rs
- examples/example_host.cpp
- examples/example_vm/example_vm.cpp
- include/evmc/evmc.h
- include/evmc/evmc.hpp
- include/evmc/helpers.h
- test/unittests/cpp_test.cpp
- test/unittests/helpers_test.cpp
Add `gas_refund` field to `evmc_result` and `evmc::Result`.
Closes #413.
Replaces #417
> Add gas refund to evmc_result

- include/evmc/evmc.hpp
- test/unittests/cpp_test.cpp
With `.raw()` method the `evmc::Result` can be passed to functions that just observe `evmc_result` and don't care about ownership. Something like:
```
void on_result(const evmc_result& res) {
// use res somehow
}
void blah() {
evmc::Result res{EVMC_SUCCESS, 1000, 0};
on_result(res.raw()); // fine after this PR
}
```
> Make Result accessible via evmc_result reference

- circle.yml
Fix fixes the CI docs upload job.
Proof it works: https://app.circleci.com/pipelines/github/ethereum/evmc/2518/workflows/d86021ce-efc8-4f17-a3d6-77faba2841ac/jobs/42204
> ci: Use SSH deploy key to upload docs to GH

- bindings/go/evmc/host.go
- bindings/java/java/src/test/java/org/ethereum/evmc/TestHostContext.java
- bindings/rust/evmc-vm/src/container.rs
- bindings/rust/evmc-vm/src/lib.rs
- include/evmc/evmc.h
Extend `evmc_tx_context` with the reference to the array of blob hashes from EIP-4844.
> Extend tx_context with EIP-4844 blob hashes

- bindings/rust/evmc-vm/src/container.rs
- bindings/rust/evmc-vm/src/lib.rs
- examples/example_host.cpp
- include/evmc/evmc.h
- include/evmc/evmc.hpp
- include/evmc/mocked_host.hpp
- test/unittests/cpp_test.cpp
- test/unittests/mocked_host_test.cpp
Add EVMC Host API for accessing and modifying transient storage (EIP-1153).
https://eips.ethereum.org/EIPS/eip-1153
Extend EVMC Host API with methods
- `get_transient_storage()`
- `set_transient_storage()`
to expose transaction-level transient storage (EIP-1153) to VM.
> Add transient storage support (EIP-1153)

- cmake/EVMC.cmake
In add_test() use the `evmc::evmc-vmtester` CMake target name directly to make it work with `CROSSCOMPILING_EMULATOR`.
> cmake: Fix evmc_add_vm_test() not working in cross-compilation

- CHANGELOG.md
- bindings/go/evmc/host.go
- bindings/java/java/src/test/java/org/ethereum/evmc/TestHostContext.java
- bindings/rust/evmc-vm/src/container.rs
- bindings/rust/evmc-vm/src/lib.rs
- include/evmc/evmc.h
Extended `tx_context` with the [EIP-7516](https://eips.ethereum.org/EIPS/eip-7516) "blob base fee" for the `BLOBBASEFEE` EVM instruction.
> Extended `tx_context` with "blob base fee"

- bindings/go/evmc/evmc.go
- bindings/go/evmc/evmc_test.go
- bindings/go/evmc/host_test.go
This PR modifies the `Execute()` function from the Go bindings to return a `Result` struct instead of a list of result values to support the retrieval of the amount of refunded gas. This information is available in [evmc.h](https://github.com/ethereum/evmc/blob/v10.1.0/include/evmc/evmc.h)'s [evmc_result](https://github.com/ethereum/evmc/blob/v10.1.0/include/evmc/evmc.h#L404-L410), but was not exposed in the Go binding so far.
> Add refund to execution result in Go binding

- bindings/go/evmc/host.go
- bindings/rust/evmc-vm/src/types.rs
- include/evmc/evmc.h
Removes the distinction between `EVMC_CREATE3` and `4`, as it is not needed anymore (see `evmone` PR referenced below). Name of the message kind pending.
> Simplify CREATE4, tidy failure conditions

- CHANGELOG.md
- CMakeLists.txt
- cmake/Hunter/init.cmake
- cmake/cable/HunterGate.cmake
- Set CMake policy settings to 3.27.
- Upgrade Hunter to v0.25.3 (with HunterGate).
> Improve compatibility with CMake 3.27

- bindings/rust/evmc-sys/Cargo.toml
- bindings/rust/evmc-sys/build.rs
This PR fixes two issues with the rust bindings:
- Constant `EMVC_ABI_VERSION` is not exported, caused by an outdated `bindgen`
- Enums are not properly rustified, due to invalid configuration.
I've run `cargo test` for the whole workspace and `cargo build` for the `example-rust-vm`.
> Fix rust bindings generation

- bindings/go/evmc/host.go
- bindings/rust/evmc-vm/src/container.rs
- bindings/rust/evmc-vm/src/lib.rs
- include/evmc/evmc.h
> Add TXCREATE transaction initcodes support - new approach

- include/evmc/bytes.hpp
- include/evmc/evmc.hpp
- include/evmc/hex.hpp
- include/evmc/mocked_host.hpp
The `std::basic_string<unsigned char>` is not standard compliant because it relies on non-standard specialization `std::char_traits<unsigned char>`.
The later has been deprecated in libc++ and will be removed in version 19.
Define our own traits `byte_traits<unsigned char>` and define the types for storing bytes as:
`std::basic_string<unsigned char, byte_traits<unsigned char>`.
> C++: Fix basic_string<unsigned char>

- lib/tooling/run.cpp
This PR will be accompanied by a PR in `evmone`, fixing the handling of top level creation msgs when validation EOF.
Here, we only replicate the behavior of creation txs for EOF - if the code begins with EOF magic it will be interpreted as an EOF creation transaction and the msg kind will be set appropriately, in order to be consumed by the `vm.execute`
> Fix support for EOF creation tx in evmc run

- README.md
evmone's tests no longer support testing other EVMC-compatible EVM implementations.
`evm-test` dropped support for external EVM implementations [in 2020](https://github.com/ethereum/evmone/pull/262/files#diff-164433c97916ccb25c2acf05bac88cb9a9be3e5fdc737f0541cd838444536a94R27).
`evmone-fuzzer` doesn't support fuzzing external EVM implemenations. It looks like they used to support fuzzing Aleth, but they dropped support for that [in 2022](https://github.com/ethereum/evmone/pull/453). The list of EVM targets is hardcoded to [just evmone](https://github.com/ethereum/evmone/blob/7bd7596c2754229f37344e10cdd49d638391f90f/test/fuzzer/fuzzer.cpp#L61).
> Remove outdated references to external tools

- bindings/rust/evmc-vm/src/lib.rs
Hello community, I am working on a project called [Dora](https://github.com/dp-labs/dora) written in Rust Integrated into EVMC Rust Bindings, I found that the `ExecuteContext` is missing methods for tload and tstore, so I opened the PR to add them.
> feat: add transient storage methods for the execute context for rust bindings

- bindings/rust/evmc-vm/src/lib.rs
Hello community, I am working on a project called [Dora](https://github.com/dp-labs/dora) written in Rust Integrated into EVMC Rust Bindings, I found that the `get_code_hash` function name typo, so I opened the PR to fix it.
> fix: get code hash func name

- bindings/go/evmc/evmc.go
- bindings/go/evmc/evmc_test.go
- bindings/go/evmc/host_test.go
- include/evmc/evmc.h
Required for EIP-7702 implementation
> Add EVMC_DELEGATED flag

- bindings/go/evmc/evmc.go
- bindings/go/evmc/evmc_test.go
- include/evmc/evmc.h
- include/evmc/helpers.h
- lib/instructions/instruction_metrics.c
- lib/instructions/instruction_names.c
- test/unittests/cpp_test.cpp
Add new `EVMC_EXPERIMENTAL` to `evmc_revision` to allow EVM implementations to expose experimental features.
> Add EXPERIMENTAL revision
